# -*- coding: utf-8 -*-
"""items.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x2m7GrZrwWCQ4Sze2MB0h2R4c6k_ibbX
"""

import scrapy

class DoubanMovieItem(scrapy.Item):
    name = scrapy.Field()
    url = scrapy.Field()
    information = scrapy.Field()
    rating = scrapy.Field()